# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kurs.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction
from PyQt5.QtGui import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.exitAction = QAction(QIcon('Tigr.png'), '& Exit')
        self.exitAction.setShortcut('Ctrl+Q')
        self.exitAction.setStatusTip('Exit application')

        self.exitAction_2 = QAction(QIcon('Tigr.png'), '& Exit')
        self.exitAction_2.setShortcut('Ctrl+O')
        self.exitAction_2.setStatusTip('Exit application')

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 841, 621))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 470, 191, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_6.setGeometry(QtCore.QRect(680, 70, 74, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(680, 30, 131, 31))
        self.label.setObjectName("label")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_36.setGeometry(QtCore.QRect(230, 370, 341, 41))
        self.lineEdit_36.setText("")
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_37.setGeometry(QtCore.QRect(680, 110, 141, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 150, 101, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setGeometry(QtCore.QRect(140, 370, 71, 41))
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_79 = QtWidgets.QLabel(self.tab_7)
        self.label_79.setGeometry(QtCore.QRect(70, 40, 51, 21))
        self.label_79.setStyleSheet("color: rgb(206, 206, 206);")
        self.label_79.setObjectName("label_79")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_38.setGeometry(QtCore.QRect(230, 60, 341, 41))
        self.lineEdit_38.setText("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_12.setGeometry(QtCore.QRect(300, 160, 191, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_80 = QtWidgets.QLabel(self.tab_7)
        self.label_80.setGeometry(QtCore.QRect(70, 60, 141, 41))
        self.label_80.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_80.setObjectName("label_80")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_28.setGeometry(QtCore.QRect(270, 120, 281, 61))
        self.lineEdit_28.setStyleSheet("font-size: 16px;")
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_29.setGeometry(QtCore.QRect(270, 230, 281, 61))
        self.lineEdit_29.setStyleSheet("font-size: 16px;")
        self.lineEdit_29.setText("")
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_19.setGeometry(QtCore.QRect(270, 340, 271, 71))
        self.pushButton_19.setStyleSheet("font-size: 20px;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_49 = QtWidgets.QLabel(self.tab_6)
        self.label_49.setGeometry(QtCore.QRect(270, 500, 311, 31))
        self.label_49.setStyleSheet("font: 15pt \"Courier\";")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(170, 120, 71, 51))
        self.label_3.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_39 = QtWidgets.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(160, 230, 81, 51))
        self.label_39.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_39.setObjectName("label_39")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 401, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 10, 74, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(130, 20, 101, 16))
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(130, 50, 261, 16))
        self.label_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(130, 80, 101, 16))
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setGeometry(QtCore.QRect(130, 110, 101, 16))
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_50 = QtWidgets.QLabel(self.groupBox_6)
        self.label_50.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_6)
        self.label_51.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_6)
        self.label_52.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_6)
        self.label_53.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_53.setObjectName("label_53")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_20.setGeometry(QtCore.QRect(320, 150, 71, 41))
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"font-size: 10px;\n"
"\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setGeometry(QtCore.QRect(130, 140, 101, 16))
        self.label_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_54 = QtWidgets.QLabel(self.groupBox_6)
        self.label_54.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_54.setObjectName("label_54")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(130, 170, 101, 16))
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        self.label_55.setGeometry(QtCore.QRect(10, 170, 101, 16))
        self.label_55.setObjectName("label_55")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 470, 801, 121))
        self.groupBox_11.setObjectName("groupBox_11")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox.setGeometry(QtCore.QRect(720, 10, 74, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_34 = QtWidgets.QLabel(self.groupBox_11)
        self.label_34.setGeometry(QtCore.QRect(200, 20, 61, 16))
        self.label_34.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_11)
        self.label_35.setGeometry(QtCore.QRect(200, 50, 261, 16))
        self.label_35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_11)
        self.label_36.setGeometry(QtCore.QRect(200, 83, 261, 16))
        self.label_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        self.label_37.setGeometry(QtCore.QRect(580, 20, 71, 20))
        self.label_37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(580, 70, 71, 20))
        self.label_38.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_24.setGeometry(QtCore.QRect(710, 70, 71, 41))
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_71 = QtWidgets.QLabel(self.groupBox_11)
        self.label_71.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupBox_11)
        self.label_72.setGeometry(QtCore.QRect(80, 50, 111, 20))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupBox_11)
        self.label_73.setGeometry(QtCore.QRect(80, 80, 111, 16))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.groupBox_11)
        self.label_74.setGeometry(QtCore.QRect(490, 20, 71, 20))
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.groupBox_11)
        self.label_75.setGeometry(QtCore.QRect(490, 70, 71, 20))
        self.label_75.setObjectName("label_75")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setGeometry(QtCore.QRect(430, 240, 391, 221))
        self.groupBox_10.setObjectName("groupBox_10")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_4.setGeometry(QtCore.QRect(310, 10, 74, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_29 = QtWidgets.QLabel(self.groupBox_10)
        self.label_29.setGeometry(QtCore.QRect(120, 30, 111, 16))
        self.label_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setGeometry(QtCore.QRect(120, 70, 261, 16))
        self.label_30.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_10)
        self.label_31.setGeometry(QtCore.QRect(120, 110, 261, 16))
        self.label_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_10)
        self.label_32.setGeometry(QtCore.QRect(120, 150, 111, 16))
        self.label_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_10)
        self.label_33.setGeometry(QtCore.QRect(120, 190, 111, 20))
        self.label_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_22.setGeometry(QtCore.QRect(310, 170, 71, 41))
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"font-size: 10px;\n"
"\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.label_66 = QtWidgets.QLabel(self.groupBox_10)
        self.label_66.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_10)
        self.label_67.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_10)
        self.label_68.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.groupBox_10)
        self.label_69.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.groupBox_10)
        self.label_70.setGeometry(QtCore.QRect(10, 190, 81, 16))
        self.label_70.setObjectName("label_70")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 240, 401, 221))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setGeometry(QtCore.QRect(130, 30, 101, 16))
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setGeometry(QtCore.QRect(130, 70, 261, 16))
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(130, 110, 261, 16))
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setGeometry(QtCore.QRect(130, 150, 101, 16))
        self.label_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setGeometry(QtCore.QRect(130, 190, 101, 16))
        self.label_28.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_23.setGeometry(QtCore.QRect(320, 170, 71, 41))
        self.pushButton_23.setStyleSheet("QPushButton {\n"
"font-size: 10px;\n"
"\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_9)
        self.comboBox_3.setGeometry(QtCore.QRect(320, 10, 74, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_61 = QtWidgets.QLabel(self.groupBox_9)
        self.label_61.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.groupBox_9)
        self.label_62.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_9)
        self.label_63.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_9)
        self.label_64.setGeometry(QtCore.QRect(10, 190, 81, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_9)
        self.label_65.setGeometry(QtCore.QRect(10, 150, 91, 20))
        self.label_65.setObjectName("label_65")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(430, 20, 391, 201))
        self.groupBox_7.setObjectName("groupBox_7")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_5.setGeometry(QtCore.QRect(310, 10, 74, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setGeometry(QtCore.QRect(120, 30, 111, 16))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(120, 60, 261, 16))
        self.label_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(120, 90, 261, 16))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(120, 150, 111, 16))
        self.label_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(120, 120, 111, 16))
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_21.setGeometry(QtCore.QRect(310, 150, 71, 41))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"font-size: 10px;\n"
"\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_56 = QtWidgets.QLabel(self.groupBox_7)
        self.label_56.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.groupBox_7)
        self.label_57.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_7)
        self.label_58.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.groupBox_7)
        self.label_59.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_7)
        self.label_60.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_60.setObjectName("label_60")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(220, 180, 401, 51))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(220, 270, 401, 51))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(220, 360, 401, 51))
        self.lineEdit_16.setText("")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(220, 100, 401, 51))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 460, 301, 41))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("color-background: red;")
        self.pushButton_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoRepeatDelay(300)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(340, 20, 191, 31))
        self.label_12.setStyleSheet("font: 18pt \"Niagara Engraved\";")
        self.label_12.setObjectName("label_12")
        self.label_40 = QtWidgets.QLabel(self.tab_2)
        self.label_40.setGeometry(QtCore.QRect(20, 100, 181, 41))
        self.label_40.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_40.setObjectName("label_40")
        self.label_45 = QtWidgets.QLabel(self.tab_2)
        self.label_45.setGeometry(QtCore.QRect(20, 370, 171, 41))
        self.label_45.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_45.setObjectName("label_45")
        self.label_77 = QtWidgets.QLabel(self.tab_2)
        self.label_77.setGeometry(QtCore.QRect(20, 280, 161, 41))
        self.label_77.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_2)
        self.label_78.setGeometry(QtCore.QRect(20, 180, 171, 41))
        self.label_78.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 241, 561))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 50, 161, 31))
        self.lineEdit_7.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(40, 100, 161, 31))
        self.lineEdit_8.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 250, 121, 23))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 512, 131, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(40, 470, 151, 31))
        self.lineEdit_11.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 141, 16))
        self.label_7.setStyleSheet("font: 9pt \"Courier New\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_18.setGeometry(QtCore.QRect(40, 150, 161, 31))
        self.lineEdit_18.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_18.setText("")
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(40, 200, 161, 31))
        self.lineEdit_19.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_19.setText("")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(50, 430, 121, 21))
        self.label_8.setStyleSheet("font: 9pt \"Courier New\";")
        self.label_8.setObjectName("label_8")
        self.label_44 = QtWidgets.QLabel(self.groupBox_4)
        self.label_44.setGeometry(QtCore.QRect(60, 290, 141, 21))
        self.label_44.setStyleSheet("font: 9pt \"Courier New\";")
        self.label_44.setObjectName("label_44")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_25.setGeometry(QtCore.QRect(50, 330, 131, 31))
        self.lineEdit_25.setStyleSheet("font: 10pt \"Impact\";")
        self.lineEdit_25.setText("")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_16.setGeometry(QtCore.QRect(50, 382, 131, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(560, 20, 251, 561))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(20, 30, 211, 61))
        self.label_10.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_10.setObjectName("label_10")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_20.setGeometry(QtCore.QRect(30, 100, 201, 41))
        self.lineEdit_20.setStyleSheet("\n"
"font: 13pt \"Impact\";")
        self.lineEdit_20.setText("")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setGeometry(QtCore.QRect(50, 230, 161, 41))
        self.pushButton_10.setStyleSheet("\n"
"border-color: rgb(255, 170, 127);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(30, 310, 191, 61))
        self.label_11.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_21.setGeometry(QtCore.QRect(30, 390, 201, 41))
        self.lineEdit_21.setStyleSheet("\n"
"font: 13pt \"Impact\";")
        self.lineEdit_21.setText("")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setGeometry(QtCore.QRect(50, 460, 161, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_30.setGeometry(QtCore.QRect(30, 160, 201, 41))
        self.lineEdit_30.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 241, 561))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(40, 90, 141, 41))
        self.lineEdit.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 150, 181, 51))
        self.lineEdit_2.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(50, 300, 121, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 171, 31))
        self.label_2.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 370, 141, 41))
        self.label_5.setStyleSheet("font: 11pt \"Courier New\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 490, 121, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_22.setGeometry(QtCore.QRect(50, 430, 131, 41))
        self.lineEdit_22.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_22.setText("")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_31.setGeometry(QtCore.QRect(50, 230, 141, 41))
        self.lineEdit_31.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_31.setText("")
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 20, 251, 561))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 150, 151, 41))
        self.lineEdit_3.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 230, 151, 51))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 201, 21))
        self.label_4.setStyleSheet("font: 13pt \"Courier New\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 320, 191, 31))
        self.label_6.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 380, 171, 61))
        self.lineEdit_5.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 470, 151, 51))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 20, 241, 561))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_41 = QtWidgets.QLabel(self.groupBox_12)
        self.label_41.setGeometry(QtCore.QRect(40, 20, 171, 16))
        self.label_41.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_41.setObjectName("label_41")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 40, 131, 21))
        self.lineEdit_12.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_13.setGeometry(QtCore.QRect(50, 70, 131, 21))
        self.lineEdit_13.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_14.setGeometry(QtCore.QRect(30, 100, 171, 21))
        self.lineEdit_14.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 160, 121, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_46 = QtWidgets.QLabel(self.groupBox_12)
        self.label_46.setGeometry(QtCore.QRect(10, 200, 231, 20))
        self.label_46.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_46.setObjectName("label_46")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_26.setGeometry(QtCore.QRect(40, 230, 151, 31))
        self.lineEdit_26.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_17.setGeometry(QtCore.QRect(50, 270, 131, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_47 = QtWidgets.QLabel(self.groupBox_12)
        self.label_47.setGeometry(QtCore.QRect(40, 450, 151, 16))
        self.label_47.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_47.setObjectName("label_47")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_27.setGeometry(QtCore.QRect(60, 480, 111, 31))
        self.lineEdit_27.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_18.setGeometry(QtCore.QRect(50, 520, 131, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_32.setGeometry(QtCore.QRect(50, 130, 131, 21))
        self.lineEdit_32.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_32.setText("")
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_25.setGeometry(QtCore.QRect(50, 410, 131, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_34.setGeometry(QtCore.QRect(70, 380, 91, 21))
        self.lineEdit_34.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_34.setText("")
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_35.setGeometry(QtCore.QRect(70, 350, 91, 21))
        self.lineEdit_35.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_35.setText("")
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_76 = QtWidgets.QLabel(self.groupBox_12)
        self.label_76.setGeometry(QtCore.QRect(40, 310, 191, 20))
        self.label_76.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_76.setObjectName("label_76")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_15.setGeometry(QtCore.QRect(560, 20, 251, 561))
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_42 = QtWidgets.QLabel(self.groupBox_15)
        self.label_42.setGeometry(QtCore.QRect(40, 50, 191, 16))
        self.label_42.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_42.setObjectName("label_42")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_23.setGeometry(QtCore.QRect(70, 100, 111, 31))
        self.lineEdit_23.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_23.setText("")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_14.setGeometry(QtCore.QRect(60, 202, 141, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_43 = QtWidgets.QLabel(self.groupBox_15)
        self.label_43.setGeometry(QtCore.QRect(60, 310, 161, 16))
        self.label_43.setStyleSheet("font: 14pt \"Courier New\";")
        self.label_43.setObjectName("label_43")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_24.setGeometry(QtCore.QRect(60, 370, 141, 31))
        self.lineEdit_24.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_24.setText("")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_15.setGeometry(QtCore.QRect(70, 432, 121, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_33.setGeometry(QtCore.QRect(70, 150, 121, 31))
        self.lineEdit_33.setStyleSheet("font: 13pt \"Impact\";")
        self.lineEdit_33.setText("")
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.tabWidget.addTab(self.tab_5, "")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(0, 620, 821, 41))
        self.label_48.setStyleSheet("font: 11pt \"Impact\";\n"
"color: rgb(198, 54, 41);\n"
"background-color: rgb(204, 204, 0);\n"
"text-align: center;")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        MainWindow.setCentralWidget(self.centralwidget)



        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 18))
        self.fileMenu = self.menubar.addMenu('&File')
        self.fileMenu.addAction(self.exitAction)
        self.fileMenu.addAction(self.exitAction_2)



        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>ы</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Создать аккаунт"))
        self.label.setText(_translate("MainWindow", "Аккаунты в сети"))
        self.lineEdit_36.setToolTip(_translate("MainWindow", "Пароль"))
        self.pushButton_5.setText(_translate("MainWindow", "Получить адрес"))
        self.label_9.setText(_translate("MainWindow", "Пароль"))
        self.label_79.setText(_translate("MainWindow", "0x59fC8D79140D5992843FFcFBd6362800d2A96e6B"))
        self.lineEdit_38.setToolTip(_translate("MainWindow", "Адрес аккаунта"))
        self.pushButton_12.setText(_translate("MainWindow", "Удалить аккаунт"))
        self.label_80.setText(_translate("MainWindow", "Адрес аккаунта"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Регистрация"))
        self.lineEdit_28.setToolTip(_translate("MainWindow", "Логин"))
        self.lineEdit_29.setToolTip(_translate("MainWindow", "Пароль"))
        self.pushButton_19.setText(_translate("MainWindow", "Войти"))
        self.label_3.setText(_translate("MainWindow", "Логин"))
        self.label_39.setText(_translate("MainWindow", "Пароль"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Авторизация"))
        self.tab.setToolTip(_translate("MainWindow", "<html><head/><body><p>Личный кабинет</p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Объекты недвежимости"))
        self.label_50.setText(_translate("MainWindow", "Общая площадь"))
        self.label_51.setText(_translate("MainWindow", "Залог"))
        self.label_52.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_53.setText(_translate("MainWindow", "ID дома"))
        self.pushButton_20.setText(_translate("MainWindow", "Просмотреть"))
        self.label_54.setText(_translate("MainWindow", "Тип недвижимости"))
        self.label_55.setText(_translate("MainWindow", "Срок эксплуатации"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Мои залоги"))
        self.pushButton_24.setText(_translate("MainWindow", "Просмотреть"))
        self.label_71.setText(_translate("MainWindow", "ID дома"))
        self.label_72.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_73.setText(_translate("MainWindow", "Адрес залогодателя"))
        self.label_74.setText(_translate("MainWindow", "Сумма залога"))
        self.label_75.setText(_translate("MainWindow", "Срок залога"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Предложения о залоге"))
        self.pushButton_22.setText(_translate("MainWindow", "Просмотреть"))
        self.label_66.setText(_translate("MainWindow", "ID дома"))
        self.label_67.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_68.setText(_translate("MainWindow", "Адрес залогодателя"))
        self.label_69.setText(_translate("MainWindow", "Сумма залога"))
        self.label_70.setText(_translate("MainWindow", "Срок залога"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Покупки"))
        self.pushButton_23.setText(_translate("MainWindow", "Просмотреть"))
        self.label_61.setText(_translate("MainWindow", "ID дома"))
        self.label_62.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_63.setText(_translate("MainWindow", "Адрес покупателя"))
        self.label_64.setText(_translate("MainWindow", "Срок"))
        self.label_65.setText(_translate("MainWindow", "Стоимость"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Предложения о продаже"))
        self.pushButton_21.setText(_translate("MainWindow", "Просмотреть"))
        self.label_56.setText(_translate("MainWindow", "ID дома"))
        self.label_57.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_58.setText(_translate("MainWindow", "Адрес покупателя"))
        self.label_59.setText(_translate("MainWindow", "Стоимость"))
        self.label_60.setText(_translate("MainWindow", "Срок"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Личный кабинет"))
        self.lineEdit_10.setToolTip(_translate("MainWindow", "Срок эксплуатации"))
        self.lineEdit_15.setToolTip(_translate("MainWindow", "Общая площадь"))
        self.lineEdit_16.setToolTip(_translate("MainWindow", "Тип недвижимости"))
        self.lineEdit_17.setToolTip(_translate("MainWindow", "Адрес владельца"))
        self.pushButton_3.setText(_translate("MainWindow", "Создать дом"))
        self.label_12.setText(_translate("MainWindow", "Создание дома"))
        self.label_40.setText(_translate("MainWindow", "Адрес владельца"))
        self.label_45.setText(_translate("MainWindow", "Тип недвижимости"))
        self.label_77.setText(_translate("MainWindow", "Общая площадь"))
        self.label_78.setText(_translate("MainWindow", "Срок эксплуатации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Админ"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Владелец"))
        self.lineEdit_7.setToolTip(_translate("MainWindow", "Номер дома"))
        self.lineEdit_8.setToolTip(_translate("MainWindow", "Цена дома"))
        self.pushButton_4.setText(_translate("MainWindow", "Создать предложение"))
        self.pushButton_7.setText(_translate("MainWindow", "Отменить предложение"))
        self.lineEdit_11.setToolTip(_translate("MainWindow", "Номер продажи"))
        self.label_7.setText(_translate("MainWindow", "Создание предложения"))
        self.lineEdit_18.setToolTip(_translate("MainWindow", "Тип объекта"))
        self.lineEdit_19.setToolTip(_translate("MainWindow", "Срок продажи"))
        self.label_8.setText(_translate("MainWindow", "Отменить продажу"))
        self.label_44.setText(_translate("MainWindow", "Получение средств"))
        self.lineEdit_25.setToolTip(_translate("MainWindow", "Номер продажи"))
        self.pushButton_16.setText(_translate("MainWindow", "Получить"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Покупатель"))
        self.label_10.setText(_translate("MainWindow", "Подтвердить покупку"))
        self.lineEdit_20.setToolTip(_translate("MainWindow", "ID продажи"))
        self.pushButton_10.setText(_translate("MainWindow", "Подтвердить"))
        self.label_11.setText(_translate("MainWindow", "Отменить покупку"))
        self.lineEdit_21.setToolTip(_translate("MainWindow", "ID продажи"))
        self.pushButton_11.setText(_translate("MainWindow", "Отменить"))
        self.lineEdit_30.setToolTip(_translate("MainWindow", "Сумма"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Продажа"))
        self.groupBox.setTitle(_translate("MainWindow", "Владелец"))
        self.lineEdit.setToolTip(_translate("MainWindow", "Номер дома"))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "Адрес получателя"))
        self.pushButton.setText(_translate("MainWindow", "Создать дарение"))
        self.label_2.setText(_translate("MainWindow", "Дарение дома"))
        self.label_5.setText(_translate("MainWindow", "Отмена дарения"))
        self.pushButton_8.setText(_translate("MainWindow", "Отменить дарение"))
        self.lineEdit_22.setToolTip(_translate("MainWindow", "ID дарения"))
        self.lineEdit_31.setToolTip(_translate("MainWindow", "Срок предложения"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Получатель"))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "ID дарения"))
        self.pushButton_6.setText(_translate("MainWindow", "Подтвердить"))
        self.label_4.setText(_translate("MainWindow", "Подтвердить дарение"))
        self.label_6.setText(_translate("MainWindow", "Отклонить дарение"))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "ID дарения"))
        self.pushButton_9.setText(_translate("MainWindow", "Отклонить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Дарение"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Владелец"))
        self.label_41.setText(_translate("MainWindow", "Заложение дома"))
        self.lineEdit_12.setToolTip(_translate("MainWindow", "ID дома"))
        self.lineEdit_13.setToolTip(_translate("MainWindow", "Цена"))
        self.lineEdit_14.setToolTip(_translate("MainWindow", "Срок предложения"))
        self.pushButton_13.setText(_translate("MainWindow", "Создать залог"))
        self.label_46.setText(_translate("MainWindow", "Подтверждение залога"))
        self.lineEdit_26.setToolTip(_translate("MainWindow", "Номер залога"))
        self.pushButton_17.setText(_translate("MainWindow", "Подтвердить"))
        self.label_47.setText(_translate("MainWindow", "Отмена залога"))
        self.lineEdit_27.setToolTip(_translate("MainWindow", "Номер залога"))
        self.pushButton_18.setText(_translate("MainWindow", "Отменить"))
        self.lineEdit_32.setToolTip(_translate("MainWindow", "Срок залога"))
        self.pushButton_25.setText(_translate("MainWindow", "Вернуть"))
        self.lineEdit_34.setToolTip(_translate("MainWindow", "Сумма"))
        self.lineEdit_35.setToolTip(_translate("MainWindow", "ID залога"))
        self.label_76.setText(_translate("MainWindow", "Возврат средств"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Залогодатель"))
        self.label_42.setText(_translate("MainWindow", "Подтвердить залог"))
        self.lineEdit_23.setToolTip(_translate("MainWindow", "ID залога"))
        self.pushButton_14.setText(_translate("MainWindow", "Подтвердить"))
        self.label_43.setText(_translate("MainWindow", "Отмена залога"))
        self.lineEdit_24.setToolTip(_translate("MainWindow", "ID залога"))
        self.pushButton_15.setText(_translate("MainWindow", "Отклонить"))
        self.lineEdit_33.setToolTip(_translate("MainWindow", "Сумма"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Залог"))
